spring.datasource.url=jdbc:h2:file:./db/testdb
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=${APP_DATABASE_USERNAME}
spring.datasource.password=${APP_DATABASE_PASSWORD}

admin.username=${APP_ADMIN_USERNAME}
admin.password=${APP_ADMIN_PASSWORD}
admin.email=${APP_ADMIN_EMAIL}
app.api.key=${APP_API_KEY}
jwt.secret = ${APP_SECRET}
jwt.expiration = ${APP_EXPIRATION}


database.url=${DB_URL:jdbc:h2:file:./db/testdb}
